### ISSUE TITLE
Documentation Bug - mapcat

### ISSUE THREAD

**Issue by will1471** [DusanKasan/Knapsack#22]
The examples for mapcat appear to be wrong.

```
Collection::from([1, 3, 3, 2])
    ->mapcat(function ($value) {
        return [[$value]];
    })
    ->toArray()
```

outputs `[[2]]` not `[[1], [3], [3], [2]]`

Presumably a call to `values` needs adding in the examples. eg

```
Collection::from([1, 3, 3, 2])
    ->mapcat(function ($value) {
        return [[$value]];
    })
    ->values()
    ->toArray()
```

**Comment by DusanKasan** [comment]
Good catch, fixed in https://github.com/DusanKasan/Knapsack/commit/5e3619e8d800d33dff31bb806a3ecda3eea6eaa5
