### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by elazar** [DusanKasan/Knapsack#24]
[Some changes](https://github.com/DusanKasan/Knapsack/compare/8.3.0...8786462) were merged in early February 2017, but never included in a tagged release, and I've got something I could use `transpose()` for. Any chance we can see a new release soon?

**Comment by DusanKasan** [comment]
Ask an you shall receive https://github.com/DusanKasan/Knapsack/releases/tag/8.4.0

But really, i was neglecting the project a bit, will do a bit of refactoring in near future.
