### ISSUE TITLE
Implement relevant native PHP interfaces

### ISSUE THREAD

**Issue by DusanKasan** [DusanKasan/Knapsack#3]
- Countable 
  - Renaming size() to count() will require new major release, wait?
  - is it worth it? Don't we want users to call count/size directly on the object?
- ArrayAccess 
  - Allows list() language construct to be used
  - Is it worth it? 4 new methods polluting the interface, how will we handle multiple same keys when unsetting, etc?

**Comment by DusanKasan** [comment]
Further thinking and tinkering:
- Can't implement ArrayAccess as it implies mutability
- Should not implement Countable as users should use the provided method instead
- size() should probably be renamed to count() in next major release as it's more familiar

**Comment by sagikazarmark** [comment]
> size() should probably be renamed to count() in next major release as it's more familiar

You could deprecate it, create count and make size an alias of it.

**Comment by DusanKasan** [comment]
Good idea. But i decided not to rename it for now, since when you are using it as a function, you don't have to provide full namespace because count() would conflict with the core count() function. We'll see if people complain about it.

Also, implementing the Countable will probably never happen as it doesn't make sense when we already have the method and we don't want to encourage users to call count().

**Comment by sagikazarmark** [comment]
No problem with `size`, just wanted to provide a solution for the BC issue.
