### ISSUE TITLE
Add more collection methods?

### ISSUE THREAD

**Issue by DusanKasan** [DusanKasan/Knapsack#5]
Currently implemented methods should be enough to express any collection operation. Nevertheless, review other popular collection libraries and their methods and consider porting them here.

No methods that are used in single scope should be ported (think form values processing).

**Comment by shameerc** [comment]
Here are the methods that I would like to see in this library.
- [scanLeft](http://www.scala-lang.org/api/2.11.8/index.html#scala.collection.Seq@scanLeft[B,That]%28z:B%29%28op:%28B,A%29=>B%29%28implicitbf:scala.collection.generic.CanBuildFrom[Repr,B,That]%29:That)
- `head($n)`, `tail($n)` - Similar to unix head and tail

I will add more as they come to my mind :)

**Comment by DusanKasan** [comment]
@shameerc Thanks for commenting. Did you have a look at take(n) method (and reverse()->take(n))? Is that what you are looking for? If not, pleas explain further. scanLeft is just an alias of `$collection->reverse()->reductions(callable)` isn't it?

I have already added (not yet pushed)
- second() // seems useless but really usefull :)
- combine($values) // uses current collection as keys, $values as values
- except($keys) // rejects every item with key found in $keys
- only($keys) // filters only items with key found in $keys
- difference(...$collections) // filters items that are in the original collection but not in any of $collections
- flip() // flips keys with values
- has($key) // checks for the existence of item with $key key

**Comment by shameerc** [comment]
Oops, I forgot about `take` (even though I'm using it everywhere). 
`scanLeft` is similar to `reductions` but without the [first yield](https://github.com/DusanKasan/Knapsack/blob/master/src/collection_functions.php#L924). I think the name `reductions` is a bit confusing in this case. 
Factorial is a perfect test for scanLeft. Here is my version.

```
$collection = Collection::range(1,5);
function scanLeft($collection, $callback, $initial) {
    $generator = function() use($collection, $callback, $initial) {
        $next = $initial;
        foreach ($collection as $key => $value) {
            $next = $callback($next, $value, $key);
            yield $next;
        }
    };
    return new Collection($generator);
}

$factorial = scanLeft($collection, function($a, $b) {
    return $a * $b;
}, 1);
$factorial->toArray();
```

To acheive the same I will have to do this

```
$factorial = $collection
    ->reductions(function ($tmp, $i) {
        return $tmp * $i;
    }, 1); 

$factorial->drop(1)->toArray();
```

**Comment by DusanKasan** [comment]
I see. But i was under the impression scanLeft returns the initial value too. As does the reductions function in scala.

See:
-  https://stackoverflow.com/questions/25884279/difference-between-scan-and-scanleft-in-scala
- https://clojuredocs.org/clojure.core/reductions

To me it makes more sense for reductions steps to include the first one (initial value).

**Comment by shameerc** [comment]
My bad, I was wrong (It's been quite long since I actually used it). I was kind of reverse engineering this :D

**Comment by DusanKasan** [comment]
Closing, as i feel the bulk of the functions was implemented. For any new requested additions a separate issue should be created.
