### ISSUE TITLE
Specifying version in composer not working

### ISSUE THREAD

**Issue by Erutan409** [DusanKasan/Knapsack#54]
Seems like no matter what version I specify in composer, the latest is being fetched.  Even then, the `utility_functions.php` doesn't seem to match what I see in master when I don't specify.

Can anyone speak to this?

**Comment by DusanKasan** [comment]
Can you provide your full (or partially redacted) composer.json/lock? This is technically not an issue with the library but i'm happy to help :) Maybe you have some dependency that depends on Knapsack?
